### ISSUE TITLE
Once I want to test my own datasets

### ISSUE THREAD

**Issue by csphuster** [GitYCC/phonetic_mlm#1]
Hi,
I want to use the model to test my own datasets in some real situations.
I have wav but I don't have data_process.

I want to generate some sentences.
Can you tell me what should I do ?
Thanks!

**Comment by GitYCC** [comment]
You can use your own ASR (Kaldi-based) to recognize wavs.

In our paper, we used open-source ASR: `vosk-model-cn-0.1` in https://alphacephei.com/vosk/models
You also can try it.
